# Generated by Django 3.1.2 on 2020-10-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('creator_name', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('times_player', models.IntegerField(default=0)),
                ('times_chosen', models.IntegerField(default=0)),
                ('prompt_id', models.IntegerField()),
                ('creator_name', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
