# Generated by Django 3.1.2 on 2020-10-22 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quipi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prompt',
        ),
        migrations.DeleteModel(
            name='Quip',
        ),
    ]
