# Generated by Django 3.1.2 on 2020-10-22 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quipi', '0002_auto_20201022_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('creator_name', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'prompt',
            },
        ),
        migrations.CreateModel(
            name='Quip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('times_player', models.IntegerField(default=0)),
                ('times_chosen', models.IntegerField(default=0)),
                ('creator_name', models.CharField(max_length=200)),
                ('accepted', models.BooleanField(default=False)),
                ('prompt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quips', to='quipi.prompt')),
            ],
            options={
                'db_table': 'quip',
            },
        ),
    ]
