# Generated by Django 3.1.2 on 2020-10-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quipi', '0004_auto_20201022_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quip',
            old_name='prompt_id',
            new_name='prompt',
        ),
    ]
